server:
  error: 
    whitelabel: 
      enabled: false
  port: 9090

spring:
  profiles:
    active: local # 로컬 폴더 활성화
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    serialization:
      fail-on-empty-beans: false

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false    # thymeleaf에 대한 캐시를 남기지 않는다. 운영시에는 true.

  datasource:
    url: jdbc:mariadb://localhost:3306/witchcrafter
    username: root
    password: java$!
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
      hibernate:
          ddl-auto: none  # DDL 쿼리 자동 생성하지 않도록 설정(create:삭제후 생성, update:변경된 스키마 적용)
      properties:
          hibernate:
              '[show_sql]': true                   # 하이버네이트가 실행하는 모든 SQL문을 콘솔로 출력
              '[format_sql]': true                 # 콘솔에 출력되는 JPA 실행 쿼리를 가독성있게 표현
              '[use_sql_comments]': true     # 디버깅이 용이하도록 SQL문 이외에 추가적인 정보를 출력
              physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl 

file:
  upload-path:
    root: C:/haupyon_folder/토이프로젝트_동숲즈팀/uploads

    material: material
    potion: potion

management: 
  endpoints:
    web:
      exposure:
        include: mappings